### ISSUE TITLE
No indicator on resume to contact via email

### ISSUE THREAD

**Issue by AlfredoTigolo** [mcfnord/tigolo#1]
I don't see on the resume an email to reach out to the original person who create the resume.

**Comment by mcfnord** [comment]
MAKE A PR

**Comment by AlfredoTigolo** [comment]
What is a pr?

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 26, 2019 at 6:41 PM, John Dempsey<notifications@github.com> wrote:   
MAKE A PR

**Comment by mcfnord** [comment]
A PULL REQUEST.

**Comment by AlfredoTigolo** [comment]
Pull request from github

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 26, 2019 at 6:43 PM, John Dempsey<notifications@github.com> wrote:   
A PULL REQUEST.
